zebracrossing/campaigns/urls.py
from django.urls import path

from . import views

app_name = 'campaigns'
urlpatterns = [
    path('', views.index, name='index'),
    path('add_campaign/', views.CampaignCreate.as_view(), name='add_campaign'),
    path('<int:pk>/', views.CampaignView.as_view(), name='detail'),
    path('<int:campaign_id>/add_booking/', views.BookingSheetCreate.as_view(), name='add_booking'),
    path('<int:campaign_id>/add_material/', views.MaterialCreate.as_view(), name='add_material'),
    path('booking/<int:pk>/', views.BookingView.as_view(), name='show_booking'),
    path('booking/<int:booking_id>/download', views.download_booking_sheet, name='download_booking_sheet'),
    path('material/<int:material_id>/download', views.download_material, name='download_material'),
]

zebracrossing/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('zebracrossing.campaigns.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('zebracrossing.registration.urls')),
]

zebracrossing/campaigns/models.py
from datetime import date
from pathlib import Path

from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import gettext_lazy as _

class TimeSlot(models.Model):
    time = models.TimeField(_('Time'))

    def __str__(self):
        return self.time.strftime("%H:%M")

    def __eq__(self, other):
        if isinstance(other, self.__class__):
            return self.time == other.time
        return False

class BookingSheet(models.Model):
    def upload_to_campaign(instance, filename):
        return f"campaigns/{instance.campaign.id}/bookings/{filename}"

    AD_TYPES = (
        ('SM', 'Social Media'),
        ('REC', 'Recorded'),
        ('LR', 'Live Read'),
        ('COMP', 'Competition')
    )
    ad_type = models.CharField(_('type'), max_length=100, choices=AD_TYPES)
    start_date = models.DateField(_('start date'))
    end_date = models.DateField(_('end date'))
    campaign = models.ForeignKey('Campaign', on_delete=models.CASCADE, related_name='booking_sheets')
    booking_sheet = models.FileField(upload_to=upload_to_campaign)
    cost = models.IntegerField()

    def clean_fields(self, exclude=None):
        super().clean_fields(exclude=exclude)
        if self.start_date > self.end_date:
            if exclude and 'start_date' in exclude:
                raise ValidationError(_("Start date is after end date"))
            else:
                raise ValidationError({'start_date': _("Start date is after end date")})
        if self.campaign is None:
            raise ValidationError(_("Campaign not specified"))

    def __str__(self):
        return self.campaign.client + " (" + \
                self.campaign.ad_agency + "): " + \
                self.start_date.strftime("%Y/%m/%d") + " - " + \
                self.end_date.strftime("%Y/%m/%d") + " (" + self.ad_type + ")"

    def __eq__(self, other):
        if isinstance(other, self.__class__):
            result = self.ad_type == other.ad_type and \
                    self.start_date == other.start_date and \
                    self.end_date == other.end_date and \
                    self.campaign == other.campaign and \
                    self.cost == other.cost
            return result
        return False

class Campaign(models.Model):
    client = models.CharField(max_length=200)
    ad_agency = models.CharField(_('advertising agency'), max_length=200)

    def __str__(self):
        return self.client + " from " + self.ad_agency

    def __eq__(self, other):
        if isinstance(other, self.__class__):
            return self.client == other.client and self.ad_agency == other.ad_agency
        return False;

    @property
    def start_date(self):
        booking_sheets = self.booking_sheets.all()
        if len(booking_sheets) == 0:
            return None
        start_date = date.max
        for sheet in booking_sheets:
            if sheet.start_date < start_date:
                start_date = sheet.start_date
        return start_date

    @property
    def end_date(self):
        booking_sheets = self.booking_sheets.all()
        if len(booking_sheets) == 0:
            return None
        end_date = date.min
        for sheet in booking_sheets:
            if sheet.end_date > end_date:
                end_date = sheet.end_date
        return end_date

    @property
    def cost(self):
        cost = 0
        for booking in self.booking_sheets.all():
            cost += booking.cost
        return cost

    def is_active(self):
        today = date.today()
        start_date = self.start_date
        end_date = self.end_date
        if start_date == None or end_date == None:
            return False
        return start_date <= today and end_date >= today

class Material(models.Model):
    def upload_to_campaign(instance, filename):
        return f"campaigns/{instance.campaign.id}/material/{filename}"

    campaign = models.ForeignKey(Campaign, on_delete=models.CASCADE, related_name='material')
    material = models.FileField(upload_to=upload_to_campaign)

    def __str__(self):
        p = Path(self.material.name)
        return f'{p.name}'

zebracrossing/campaigns/forms.py
from django import forms

from zebracrossing.forms import CalendarWidget, FileWidget
from .models import BookingSheet, Campaign, TimeSlot, Material


class BookingSheetForm(forms.ModelForm):
    class Meta:
        model = BookingSheet
        fields = ['booking_sheet', 'ad_type', 'start_date', 'end_date', 'cost']
        widgets = {
            'booking_sheet': FileWidget,
            'start_date': CalendarWidget,
            'end_date': CalendarWidget,
        }

    def clean(self):
        cleaned_data = super().clean()
        old_cleaned_data = cleaned_data
        return cleaned_data

    def clean_time_slots_UNUSED(cleaned_data):
        """
        Places ads in time slots based on the provided times and flexibility. It
        is currently unused because it needs a better way of displaying
        timeslots and allowing them to be selected. Once that is fixed, this
        should be called from clean().
        """
        for slot in old_cleaned_data['time_slots']:
            current_bookings = BookingSheet.objects.filter(time_slots__time=slot.time)
            if current_bookings.count() > 0:
                time_slots = TimeSlot.objects.all().order_by('time')
                flexibility = cleaned_data.get('time_slot_flexiblility')
                index = 0
                for start_time_slot in time_slots:
                    if (start_time_slot == slot):
                        break
                    index += 1
                if (index >= time_slots.count()):
                    index = time_slots.count() - 1
                end_index = min(time_slots.count(), index + flexibility + 1)
                time_slots = time_slots[index:end_index]
                min_slot = slot
                for start_time_slot in time_slots:
                    current_min = BookingSheet.objects.filter(time_slots__time=min_slot.time)
                    bookings = BookingSheet.objects.filter(time_slots__time=start_time_slot.time)
                    if bookings.count() < current_min.count():
                        min_slot = start_time_slot
                cleaned_data['time_slots'].filter(id=slot.id).update(time=min_slot.time)
        cleaned_data['time_slot_flexiblility'] = 0


class CampaignForm(forms.ModelForm):
    class Meta:
        model = Campaign
        fields = ['client', 'ad_agency']

class MaterialForm(forms.ModelForm):
    class Meta:
        model = Material
        fields = ['material',]
        widgets = {
            'material': FileWidget,
        }

zebracrossing/campaigns/views.py
from datetime import date, timedelta
import mimetypes

from django.contrib.auth.decorators import login_required
from django.contrib.auth import mixins
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse
from django.views.generic import DetailView
from django.views.generic.edit import CreateView
from django.urls import reverse, reverse_lazy

from zebracrossing.forms import CalendarWidget, FileWidget
from .models import BookingSheet, Campaign, Material
from .forms import BookingSheetForm, CampaignForm, MaterialForm

class CampaignView(mixins.LoginRequiredMixin, DetailView):
    model = Campaign

class BookingView(mixins.LoginRequiredMixin, DetailView):
    model = BookingSheet

@login_required
def index(request):
    campaigns = Campaign.objects.all()
    active_campaigns = []
    upcoming_campaigns = []
    past_campaigns = []
    for campaign in campaigns:
        start_date = campaign.start_date
        end_date = campaign.end_date
        if campaign.is_active():
            active_campaigns.append(campaign)
        elif end_date != None and end_date < date.today():
            past_campaigns.append(campaign)
        elif start_date != None and start_date - date.today() < timedelta(weeks=1):
            upcoming_campaigns.append(campaign)

    context = {
        'active_campaigns': active_campaigns,
        'upcoming_campaigns': upcoming_campaigns,
        'past_campaigns': past_campaigns,
    }
    return render(request, 'campaigns/index.html', context)

class BookingSheetCreate(mixins.LoginRequiredMixin, CreateView):
    template_name = 'campaigns/add_update_object.html'
    form_class = BookingSheetForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Upload Booking Sheet'
        context['url'] = reverse('campaigns:add_booking', args=[self.kwargs['campaign_id']])
        return context

    def get_success_url(self):
        return redirect('campaigns:detail', self.kwargs['campaign_id'])

class MaterialCreate(mixins.LoginRequiredMixin, CreateView):
    template_name = 'campaigns/add_update_object.html'
    form_class = MaterialForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Upload Material'
        context['url'] = reverse('campaigns:add_material', args=[self.kwargs['campaign_id']])
        return context

    def get_success_url(self):
        return redirect('campaigns:detail', self.kwargs['campaign_id'])

class CampaignCreate(mixins.LoginRequiredMixin, CreateView):
    template_name = 'campaigns/add_update_object.html'
    form_class = CampaignForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Add New Campaign'
        context['url'] = reverse('campaigns:add_campaign')
        return context

    def get_success_url(self):
        return redirect('campaigns:add_booking', self.obj.id)

@login_required
def download_booking_sheet(request, booking_id):
    booking = get_object_or_404(BookingSheet, pk=booking_id)
    return download_item(request, booking.booking_sheet)

@login_required
def download_material(request, material_id):
    material = get_object_or_404(Material, pk=material_id)
    return download_item(request, material.material)

@login_required
def download_item(request, item):
    mimetype = mimetypes.guess_type(item.url)[0]
    response = HttpResponse(item, content_type=mimetype)
    response['Content-Disposition'] = f'filename="{item.name}"'
    return response

zebracrossing/campaigns/templates/campaigns/add_update_object.html
{% extends 'zebracrossing/base.html' %}
{% load static widget_tweaks %}

{% block extra_head %}
{{ block.super }}
{{ form.media }}
{% endblock %}

{% block content %}
<div class="col-sm-6">
  <form enctype="multipart/form-data" action="{{ url }}" method="post">
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group">
      {% for error in field.errors %}
      <div class="alert alert-danger" role="alert">
        {{ error }}
      </div>
      {% endfor %}
      {% if field|widget_type == "filewidget" %}
      <div class="custom-file">
        {{ field|add_class:'custom-file-input' }}
        <label class="custom-file-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
      </div>
      {% elif field|widget_type == "checkboxselectmultiple" %}
      <label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}:</label>
      {% for field in field %}
      <div class="form-check">
        {{ field }}
      </div>
      {% endfor %}
      {% else %}
      <label class="control-label" for="{{ field.id_for_label }}">{{ field.label }}:</label>
      {{ field|add_class:'form-control' }}
      {% endif %}
    </div>
    {% endfor %}
    <div class="form-group">
      <button class="btn btn-primary" id="submit-btn" type="submit">Add</button>
    </div>
  </form>
</div>
{% endblock %}

zebracrossing/campaigns/templates/campaigns/bookingsheet_detail.html
{% extends 'zebracrossing/base.html' %}
{% block content %}

<div id="time_slots" class="row">
  <div class="col-sm-8">
    <h2>Time Slots</h2>
  </div>
  <div class="col-sm-4">
    <a href="{% url 'campaigns:download_booking_sheet' bookingsheet.id %}"
      class="btn btn-primary heading-btn" role="buttom">Download Booking Sheet</a>
  </div>
</div>
{% if bookingsheet.time_slots %}
  <ul class="list-group">
    {% for time_slot in bookingsheet.time_slots.all %}
    <li class="list-group-item">{{ time_slot }}</li>
    {% endfor %}
  </ul>
{% endif %}
{% endblock %}

zebracrossing/campaigns/templates/campaigns/campaign_detail.html
{% extends 'zebracrossing/base.html' %}
{% block content %}
<h1>{{ campaign }}</h1>
<p>
Client: {{ campaign.client }}<br>
Ad Agency: {{ campaign.ad_agency }}<br>
Cost: R {{ campaign.cost }}<br>
</p>

<div id="booking_sheets" class="row">
  <div class="col-sm-10">
    <h2>Booking Sheets</h2>
  </div>
  <div class="col-sm-2">
    <a href="{% url 'campaigns:add_booking' campaign.id %}" class="btn btn-primary heading-btn" role="button">Add booking</a>
  </div>
</div>

{% if campaign.booking_sheets %}
  <ul class="list-group">
    {% for sheet in campaign.booking_sheets.all %}
    <li class="list-group-item"><a href="{% url 'campaigns:show_booking' sheet.id %}">{{ sheet.get_ad_type_display }}: {{ sheet.start_date }} - {{ sheet.end_date }}</a></li>
    {% endfor %}
  </ul>
{% endif %}

<div id="material" class="row">
  <div class="col-sm-10">
    <h2>Material</h2>
  </div>
  <div class="col-sm-2">
    <a href="{% url 'campaigns:add_material' campaign.id %}" class="btn btn-primary heading-btn" role="button">Add material</a>
  </div>
</div>

{% if campaign.material %}
  <ul class="list-group">
    {% for material in campaign.material.all %}
    <li class="list-group-item"><a href="{% url 'campaigns:download_material' material.id %}">{{ material }}</a></li>
    {% endfor %}
  </ul>
{% endif %}
{% endblock %}

zebracrossing/campaigns/templates/campaigns/index.html
{% extends 'zebracrossing/base.html' %}
{% block content %}
<div id=campaign-heading" class="row">
  <div class="col-sm-8">
    <h1>Campaigns</h1>
  </div>
  <div class="col-sm-4">
    <a href="{% url 'campaigns:add_campaign' %}" class="btn btn-primary heading-btn" role="button">Add campaign</a>
  </div>
</div>
<div id="campaigns" class="row">
  <div class="col-lg-4">
    <h2>Active Campaigns</h2>
    {% if active_campaigns %}
      <ul class="list-group">
    {% for campaign in active_campaigns %}
      <li class="list-group-item"><a href="{% url 'campaigns:detail' campaign.id %}">{{ campaign }}</a></li>
    {% endfor %}
      </ul>
    {% else %}
      <p>No campaigns are currently active</p>
    {% endif %}
  </div>
  <div class="col-lg-4">
    <h2>Upcoming Campaigns</h2>
    {% if upcoming_campaigns %}
      <ul class="list-group">
    {% for campaign in upcoming_campaigns %}
      <li class="list-group-item"><a href="{% url 'campaigns:detail' campaign.id %}">{{ campaign }}</a></li>
    {% endfor %}
      </ul>
    {% else %}
      <p>No campaigns are currently coming up</p>
    {% endif %}
  </div>
  <div class="col-lg-4">
    <h2>Past Campaigns</h2>
    {% if past_campaigns %}
      <ul class="list-group">
    {% for campaign in past_campaigns %}
      <li class="list-group-item"><a href="{% url 'campaigns:detail' campaign.id %}">{{ campaign }}</a></li>
    {% endfor %}
      </ul>
    {% else %}
      <p>There are no past campaigns</p>
    {% endif %}
  </div>
{% endblock %}